# country_mapping.py
COUNTRY_MAPPINGS = {
    "AF": {"name": "Afghanistan",               "aliases": ["Afghanistan", "AF", "Afganistan"]},
    "AL": {"name": "Albania",                   "aliases": ["Albania", "AL", "Shqipëri"]},
    "DZ": {"name": "Algérie",                   "aliases": ["Algeria", "DZ", "Algérie"]},
    "AS": {"name": "Samoa thuộc Mỹ",            "aliases": ["American Samoa", "AS"]},
    "AD": {"name": "Andorra",                   "aliases": ["Andorra", "AD"]},
    "AO": {"name": "Angola",                    "aliases": ["Angola", "AO"]},
    "AR": {"name": "Argentina",                 "aliases": ["Argentina", "AR"]},
    "AM": {"name": "Armenia",                   "aliases": ["Armenia", "AM", "Hayastan"]},
    "AU": {"name": "Úc",                       "aliases": ["Australia", "AU"]},
    "AT": {"name": "Áo",                       "aliases": ["Austria", "AT", "Österreich"]},
    "AZ": {"name": "Azerbaijan",                "aliases": ["Azerbaijan", "AZ", "Azərbaycan"]},
    "BD": {"name": "Bangladesh",                "aliases": ["Bangladesh", "BD", "বাংলাদেশ"]},
    "BY": {"name": "Belarus",                   "aliases": ["Belarus", "BY", "Беларусь"]},
    "BE": {"name": "Bỉ",                       "aliases": ["Belgium", "BE", "België", "Belgique"]},
    "BZ": {"name": "Belize",                    "aliases": ["Belize", "BZ"]},
    "BJ": {"name": "Benin",                     "aliases": ["Benin", "BJ", "Bénin"]},
    "BT": {"name": "Bhutan",                    "aliases": ["Bhutan", "BT"]},
    "BO": {"name": "Bolivia",                   "aliases": ["Bolivia", "BO", "Bolivia (Plurinational State of)"]},
    "BA": {"name": "Bosna và Hercegovina",      "aliases": ["Bosnia", "BA", "Bosnia and Herzegovina"]},
    "BW": {"name": "Botswana",                  "aliases": ["Botswana", "BW"]},
    "BR": {"name": "Brazil",                    "aliases": ["Brazil", "BR", "Brasil"]},
    "BN": {"name": "Brunei",                    "aliases": ["Brunei", "BN", "Brunei Darussalam"]},
    "BG": {"name": "Bulgaria",                  "aliases": ["Bulgaria", "BG", "България"]},
    "BF": {"name": "Burkina Faso",              "aliases": ["Burkina Faso", "BF"]},
    "BI": {"name": "Burundi",                   "aliases": ["Burundi", "BI"]},
    "KH": {"name": "Campuchia",                 "aliases": ["Cambodia", "KH", "Kampuchea"]},
    "CM": {"name": "Cameroon",                  "aliases": ["Cameroon", "CM", "Cameroun"]},
    "CA": {"name": "Canada",                    "aliases": ["Canada", "CA"]},
    "CV": {"name": "Cape Verde",                "aliases": ["Cabo Verde", "CV"]},
    "CF": {"name": "Cộng hòa Trung Phi",        "aliases": ["Central African Republic", "CF"]},
    "TD": {"name": "Tchad",                     "aliases": ["Chad", "TD", "Tchad"]},
    "CL": {"name": "Chile",                     "aliases": ["Chile", "CL"]},
    "CN": {"name": "Trung Quốc",                "aliases": ["China", "CN", "PRC", "China – PRC"]},
    "CO": {"name": "Colombia",                  "aliases": ["Colombia", "CO"]},
    "KM": {"name": "Comoros",                   "aliases": ["Comoros", "KM", "Comores"]},
    "CG": {"name": "Congo",                     "aliases": ["Congo", "CG", "Republic of the Congo"]},
    "CD": {"name": "Congo (DC)",                "aliases": ["DRC", "Democratic Republic of the Congo", "CD"]},
    "CR": {"name": "Costa Rica",                "aliases": ["Costa Rica", "CR"]},
    "CI": {"name": "Bờ Biển Ngà",               "aliases": ["Côte d'Ivoire", "Ivory Coast", "CI"]},
    "HR": {"name": "Croatia",                   "aliases": ["Croatia", "HR", "Hrvatska"]},
    "CU": {"name": "Cuba",                      "aliases": ["Cuba", "CU"]},
    "CY": {"name": "Síp",                       "aliases": ["Cyprus", "CY", "Κύπρος"]},
    "CZ": {"name": "Cộng hòa Séc",              "aliases": ["Czech Republic", "CZ", "Česká"]},
    "DK": {"name": "Đan Mạch",                  "aliases": ["Denmark", "DK", "Danmark"]},
    "DJ": {"name": "Djibouti",                  "aliases": ["Djibouti", "DJ"]},
    "DM": {"name": "Dominica",                  "aliases": ["Dominica", "DM"]},
    "DO": {"name": "Dominican Republic",        "aliases": ["Dominican Republic", "DO", "Dominicana"]},
    "EC": {"name": "Ecuador",                   "aliases": ["Ecuador", "EC"]},
    "EG": {"name": "Ai Cập",                    "aliases": ["Egypt", "EG", "Misr"]},
    "SV": {"name": "El Salvador",               "aliases": ["El Salvador", "SV"]},
    "GQ": {"name": "Equatorial Guinea",         "aliases": ["Equatorial Guinea", "GQ"]},
    "ER": {"name": "Eritrea",                   "aliases": ["Eritrea", "ER"]},
    "EE": {"name": "Estonia",                   "aliases": ["Estonia", "EE", "Eesti"]},
    "ET": {"name": "Ethiopia",                  "aliases": ["Ethiopia", "ET", "ኢትዮጵያ"]},
    "FJ": {"name": "Fiji",                      "aliases": ["Fiji", "FJ"]},
    "FI": {"name": "Phần Lan",                  "aliases": ["Finland", "FI", "Suomi"]},
    "FR": {"name": "Pháp",                      "aliases": ["France", "FR", "République française"]},
    "GA": {"name": "Gabon",                     "aliases": ["Gabon", "GA"]},
    "GM": {"name": "Gambia",                    "aliases": ["Gambia", "GM"]},
    "GE": {"name": "Georgia",                   "aliases": ["Georgia", "GE", "საქართველო"]},
    "DE": {"name": "Đức",                       "aliases": ["Germany", "DE", "Deutschland"]},
    "GH": {"name": "Ghana",                     "aliases": ["Ghana", "GH"]},
    "GR": {"name": "Hy Lạp",                    "aliases": ["Greece", "GR", "Ελλάδα"]},
    "GT": {"name": "Guatemala",                 "aliases": ["Guatemala", "GT"]},
    "GN": {"name": "Guinea",                    "aliases": ["Guinea", "GN"]},
    "GW": {"name": "Guinea-Bissau",             "aliases": ["Guinea-Bissau", "GW"]},
    "GY": {"name": "Guyana",                    "aliases": ["Guyana", "GY"]},
    "HT": {"name": "Haiti",                     "aliases": ["Haiti", "HT"]},
    "HN": {"name": "Honduras",                  "aliases": ["Honduras", "HN"]},
    "HU": {"name": "Hungary",                   "aliases": ["Hungary", "HU", "Magyarország"]},
    "IS": {"name": "Iceland",                   "aliases": ["Iceland", "IS", "Ísland"]},
    "IN": {"name": "Ấn Độ",                     "aliases": ["India", "IN", "Bhārat"]},
    "ID": {"name": "Indonesia",                 "aliases": ["Indonesia", "ID", "Nusantara"]},
    "IR": {"name": "Iran",                      "aliases": ["Iran", "IR", "ایران"]},
    "IQ": {"name": "Iraq",                      "aliases": ["Iraq", "IQ", "العراق"]},
    "IE": {"name": "Ireland",                   "aliases": ["Ireland", "IE"]},
    "IL": {"name": "Israel",                    "aliases": ["Israel", "IL", "Medinat Yisrael"]},
    "IT": {"name": "Ý",                         "aliases": ["Italy", "IT", "Italia"]},
    "JM": {"name": "Jamaica",                   "aliases": ["Jamaica", "JM"]},
    "JP": {"name": "Nhật Bản",                  "aliases": ["Japan", "JP", "Nippon", "日本"]},
    "JO": {"name": "Jordan",                    "aliases": ["Jordan", "JO"]},
    "KZ": {"name": "Kazakhstan",                "aliases": ["Kazakhstan", "KZ"]},
    "KE": {"name": "Kenya",                     "aliases": ["Kenya", "KE"]},
    "KI": {"name": "Kiribati",                  "aliases": ["Kiribati", "KI"]},
    "KP": {"name": "Triều Tiên",                "aliases": ["North Korea", "KP", "DPRK"]},
    "KR": {"name": "Hàn Quốc",                  "aliases": ["South Korea", "KR", "Republic of Korea"]},
    "KW": {"name": "Kuwait",                    "aliases": ["Kuwait", "KW"]},
    "KG": {"name": "Kyrgyzstan",                "aliases": ["Kyrgyzstan", "KG"]},
    "LA": {"name": "Lào",                       "aliases": ["Laos", "LA", "Lao PDR"]},
    "LV": {"name": "Latvia",                    "aliases": ["Latvia", "LV", "Latvija"]},
    "LB": {"name": "Lebanon",                   "aliases": ["Lebanon", "LB", "لبنان"]},
    "LS": {"name": "Lesotho",                   "aliases": ["Lesotho", "LS"]},
    "LR": {"name": "Liberia",                   "aliases": ["Liberia", "LR"]},
    "LY": {"name": "Libya",                     "aliases": ["Libya", "LY"]},
    "LI": {"name": "Liechtenstein",             "aliases": ["Liechtenstein", "LI"]},
    "LT": {"name": "Lithuania",                 "aliases": ["Lithuania", "LT", "Lietuva"]},
    "LU": {"name": "Luxembourg",                "aliases": ["Luxembourg", "LU", "Lëtzebuerg"]},
    "MG": {"name": "Madagascar",                "aliases": ["Madagascar", "MG"]},
    "MW": {"name": "Malawi",                    "aliases": ["Malawi", "MW"]},
    "MY": {"name": "Malaysia",                  "aliases": ["Malaysia", "MY"]},
    "MV": {"name": "Maldives",                  "aliases": ["Maldives", "MV"]},
    "ML": {"name": "Mali",                      "aliases": ["Mali", "ML"]},
    "MT": {"name": "Malta",                     "aliases": ["Malta", "MT"]},
    "MH": {"name": "Marshall Islands",          "aliases": ["Marshall Islands", "MH"]},
    "MR": {"name": "Mauritania",                "aliases": ["Mauritania", "MR"]},
    "MU": {"name": "Mauritius",                 "aliases": ["Mauritius", "MU"]},
    "MX": {"name": "Mexico",                    "aliases": ["Mexico", "MX", "México"]},
    "FM": {"name": "Micronesia",                "aliases": ["Micronesia", "FM", "Federated States of Micronesia"]},
    "MD": {"name": "Moldova",                   "aliases": ["Moldova", "MD", "Republic of Moldova"]},
    "MC": {"name": "Monaco",                    "aliases": ["Monaco", "MC"]},
    "MN": {"name": "Mông Cổ",                   "aliases": ["Mongolia", "MN", "Монгол"]},
    "ME": {"name": "Montenegro",                "aliases": ["Montenegro", "ME"]},
    "MA": {"name": "Ma Rốc",                    "aliases": ["Morocco", "MA"]},
    "MZ": {"name": "Mozambique",                "aliases": ["Mozambique", "MZ"]},
    "MM": {"name": "Myanmar",                   "aliases": ["Myanmar", "MM", "Burma"]},
    "NA": {"name": "Namibia",                   "aliases": ["Namibia", "NA"]},
    "NR": {"name": "Nauru",                     "aliases": ["Nauru", "NR"]},
    "NP": {"name": "Nepal",                     "aliases": ["Nepal", "NP"]},
    "NL": {"name": "Hà Lan",                    "aliases": ["Netherlands", "NL", "Holland"]},
    "NZ": {"name": "New Zealand",               "aliases": ["New Zealand", "NZ"]},
    "NI": {"name": "Nicaragua",                 "aliases": ["Nicaragua", "NI"]},
    "NE": {"name": "Niger",                     "aliases": ["Niger", "NE"]},
    "NG": {"name": "Nigeria",                   "aliases": ["Nigeria", "NG"]},
    "NO": {"name": "Na Uy",                     "aliases": ["Norway", "NO", "Norge"]},
    "OM": {"name": "Oman",                      "aliases": ["Oman", "OM"]},
    "PK": {"name": "Pakistan",                  "aliases": ["Pakistan", "PK"]},
    "PS": {"name": "Palestine",                 "aliases": ["Palestine", "PS"]},
    "PA": {"name": "Panama",                    "aliases": ["Panama", "PA"]},
    "PG": {"name": "Papua New Guinea",          "aliases": ["Papua New Guinea", "PG"]},
    "PY": {"name": "Paraguay",                  "aliases": ["Paraguay", "PY"]},
    "PE": {"name": "Peru",                      "aliases": ["Peru", "PE"]},
    "PH": {"name": "Philippines",               "aliases": ["Philippines", "PH"]},
    "PL": {"name": "Ba Lan",                    "aliases": ["Poland", "PL", "Polska"]},
    "PT": {"name": "Bồ Đào Nha",                "aliases": ["Portugal", "PT", "Portugal"]},
    "QA": {"name": "Qatar",                     "aliases": ["Qatar", "QA"]},
    "RO": {"name": "Romania",                   "aliases": ["Romania", "RO"]},
    "RU": {"name": "Nga",                       "aliases": ["Russia", "RU", "России"]},
    "RW": {"name": "Rwanda",                    "aliases": ["Rwanda", "RW"]},
    "KN": {"name": "Saint Kitts và Nevis",      "aliases": ["Saint Kitts", "KN"]},
    "LC": {"name": "Saint Lucia",               "aliases": ["Saint Lucia", "LC"]},
    "VC": {"name": "Saint Vincent và Grenadines","aliases": ["Saint Vincent", "VC"]},
    "WS": {"name": "Samoa",                     "aliases": ["Samoa", "WS"]},
    "SM": {"name": "San Marino",                "aliases": ["San Marino", "SM"]},
    "ST": {"name": "São Tomé và Príncipe",      "aliases": ["Sao Tome", "ST"]},
    "SA": {"name": "Ả Rập Xê Út",               "aliases": ["Saudi Arabia", "SA"]},
    "SN": {"name": "Senegal",                   "aliases": ["Senegal", "SN"]},
    "RS": {"name": "Serbia",                    "aliases": ["Serbia", "RS"]},
    "SC": {"name": "Seychelles",                "aliases": ["Seychelles", "SC"]},
    "SL": {"name": "Sierra Leone",              "aliases": ["Sierra Leone", "SL"]},
    "SG": {"name": "Singapore",                 "aliases": ["Singapore", "SG"]},
    "SK": {"name": "Slovakia",                  "aliases": ["Slovakia", "SK", "Slovensko"]},
    "SI": {"name": "Slovenia",                  "aliases": ["Slovenia", "SI", "Slovenija"]},
    "SB": {"name": "Quần đảo Solomon",          "aliases": ["Solomon Islands", "SB"]},
    "SO": {"name": "Somalia",                   "aliases": ["Somalia", "SO"]},
    "ZA": {"name": "Nam Phi",                   "aliases": ["South Africa", "ZA", "RSA"]},
    "KR": {"name": "Hàn Quốc",                  "aliases": ["South Korea", "KR", "Republic of Korea"]},
    "SS": {"name": "Nam Sudan",                 "aliases": ["South Sudan", "SS"]},
    "ES": {"name": "Tây Ban Nha",               "aliases": ["Spain", "ES", "España"]},
    "LK": {"name": "Sri Lanka",                 "aliases": ["Sri Lanka", "LK"]},
    "SD": {"name": "Sudan",                     "aliases": ["Sudan", "SD"]},
    "SR": {"name": "Suriname",                  "aliases": ["Suriname", "SR"]},
    "SE": {"name": "Thụy Điển",                 "aliases": ["Sweden", "SE", "Sverige"]},
    "CH": {"name": "Thụy Sĩ",                   "aliases": ["Switzerland", "CH", "Schweiz"]},
    "SY": {"name": "Syria",                     "aliases": ["Syria", "SY", "سوريا"]},
    "TJ": {"name": "Tajikistan",                "aliases": ["Tajikistan", "TJ"]},
    "TZ": {"name": "Tanzania",                  "aliases": ["Tanzania", "TZ"]},
    "TH": {"name": "Thái Lan",                 "aliases": ["Thailand", "TH", "Thai Lan"]},
    "TL": {"name": "Timor-Leste",               "aliases": ["Timor-Leste", "TL", "East Timor"]},
    "TG": {"name": "Togo",                      "aliases": ["Togo", "TG"]},
    "TO": {"name": "Tonga",                     "aliases": ["Tonga", "TO"]},
    "TT": {"name": "Trinidad và Tobago",        "aliases": ["Trinidad and Tobago", "TT"]},
    "TN": {"name": "Tunisia",                   "aliases": ["Tunisia", "TN"]},
    "TR": {"name": "Thổ Nhĩ Kỳ",               "aliases": ["Turkey", "TR", "Türkiye"]},
    "TM": {"name": "Turkmenistan",              "aliases": ["Turkmenistan", "TM"]},
    "UG": {"name": "Uganda",                    "aliases": ["Uganda", "UG"]},
    "UA": {"name": "Ucraina",                   "aliases": ["Ukraine", "UA"]},
    "AE": {"name": "Các Tiểu vương quốc Ả Rập Thống nhất","aliases": ["UAE", "United Arab Emirates", "AE"]},
    "GB": {"name": "Anh",                       "aliases": ["United Kingdom", "UK", "GB", "England"]},
    "US": {"name": "Hoa Kỳ",                    "aliases": ["United States", "USA", "US", "America"]},
    "UY": {"name": "Uruguay",                   "aliases": ["Uruguay", "UY"]},
    "UZ": {"name": "Uzbekistan",                "aliases": ["Uzbekistan", "UZ"]},
    "VU": {"name": "Vanuatu",                   "aliases": ["Vanuatu", "VU"]},
    "VA": {"name": "Vatican",                   "aliases": ["Holy See", "Vatican City", "VA"]},
    "VE": {"name": "Venezuela",                 "aliases": ["Venezuela", "VE"]},
    "VN": {"name": "Việt Nam",                  "aliases": ["Vietnam", "VN", "Viet Nam"]},
    "EH": {"name": "Tây Sahara",                "aliases": ["Western Sahara", "EH"]},
    "YE": {"name": "Yemen",                     "aliases": ["Yemen", "YE"]},
    "ZM": {"name": "Zambia",                    "aliases": ["Zambia", "ZM"]},
    "ZW": {"name": "Zimbabwe",                  "aliases": ["Zimbabwe", "ZW"]}
}


def get_keywords_from_country(country_code_or_name):
    """Lấy tất cả từ khóa có thể của một quốc gia từ mã hoặc tên"""
    # Chuẩn hóa đầu vào
    if not country_code_or_name:
        return []
    
    input_text = str(country_code_or_name).strip()
    
    # 1. Kiểm tra xem đầu vào có phải là mã quốc gia không
    if input_text.upper() in COUNTRY_MAPPINGS:
        code = input_text.upper()
        info = COUNTRY_MAPPINGS[code]
        return [code, info["name"]] + info["aliases"]
    
    # 2. Tìm trong tên chính thức
    for code, info in COUNTRY_MAPPINGS.items():
        if input_text.lower() == info["name"].lower():
            return [code, info["name"]] + info["aliases"]
    
    # 3. Tìm trong aliases
    for code, info in COUNTRY_MAPPINGS.items():
        for alias in info["aliases"]:
            if input_text.lower() == alias.lower():
                return [code, info["name"]] + info["aliases"]
    
    # 4. Tìm một phần
    for code, info in COUNTRY_MAPPINGS.items():
        # Kiểm tra tên chính
        if input_text.lower() in info["name"].lower() or info["name"].lower() in input_text.lower():
            return [code, info["name"]] + info["aliases"]
        
        # Kiểm tra aliases
        for alias in info["aliases"]:
            if input_text.lower() in alias.lower() or alias.lower() in input_text.lower():
                return [code, info["name"]] + info["aliases"]
    
    # Nếu không tìm thấy, trả về input ban đầu
    return [input_text]